modLoader="javafml"
loaderVersion="[47,)"
license="Apache License version 2.0"

[[mods]]
modId="prehistoric_world"
version="1.0.0"
displayName="Prehistoric world"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/prehistoric-world-t"
credits="thatdudew"
authors="thatdudew"
description="prehistoric_world  "

[[dependencies.prehistoric_world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




